#pragma once
#include "CoreMinimal.h"
#include "EAchievementType.generated.h"

UENUM(BlueprintType)
enum class EAchievementType : uint8 {
    NONE_ACHIVE,
    FIELD_COMMAND_SUCCESS_COUNT,
    FIELD_COMMAND_INFORMATION_SUCCESS_COUNT,
    FOLLOWING_NPC_COUNT,
    MAIN_STORY_CLEAR,
    MAIN_STORY_CLEAR_COUNT,
    SUB_STORY_CLEAR,
    SUB_STORY_CLEAR_COUNT,
    ACQUISITION_ABILITY,
    ACQUISITION_ABILITY_COUNT,
    ACQUISITION_DEVINE_ABILITY_COUNT,
    ACQUISITION_SUPPORT_ABILITY_COUNT,
    ACQUISITION_ADVANCED_ABILITY_COUNT,
    GET_ITEM,
    GET_ITEM_COUNT,
    GET_JOB_ITEM_COUNT,
    GET_SPITEM_COUNT_BY_SPITEM_TYPE,
    VISIT_LEVEL_COUNT,
    LINER_SHIP_COUNT,
    JOINED_PLAYER_CHARACTER_COUNT,
    USED_BOOST_ATTACK_COUNT,
    BREAK_COUNT,
    DAMAGE_VALUE,
    MAIN_STORY_CLEAR_ALL_CHAPTER,
    LAST_CHAPTER_CLEAR,
    EPILOGUE_CLEAR,
    COUPLE_STORY_CLEAR,
    SWOON_NPC_UNIQUE_COUNT,
    ACHIEVEMENT_ALL_CLEAR,
    EX_BOSS_CLEAR,
};

