#pragma once
#include "CoreMinimal.h"
#include "EBATTLE_VOICE_TYPE.generated.h"

UENUM(BlueprintType)
enum class EBATTLE_VOICE_TYPE : uint8 {
    eBATTLE_VOICE_NONE,
    eBATTLE_START,
    eBATTLE_VICTORY,
    eORDER_START,
    eTAKE_DAMAGE,
    eON_DEAD,
    eNORMAL_ATTACK,
    eNORMAL_ATTACK_LAST_HIT,
    eON_BOOST,
    eOPEN_WEAKNESS,
    eBREAK_ENEMY,
    eON_AVOID,
    eKILL_ENEMY,
    eON_RECOVERED,
    eON_REVIVED,
    eUSE_ITEM_TO_PARTY,
    eUSE_ITEM_TO_ENEMY,
    ePLAY_GUARD,
    ePLAY_ABILITY,
    eON_POTENTIALITY_ACTION,
    eINVADE_MONSTER,
    eCALL_SUPPORTER,
    eCALLED_SUPPORTER,
    ePLAY_LEARN_ABILITY,
    ePREPARATION_RECOVERY,
    ePREPARATION_ATTACK,
    eON_INVALID_DISEASE,
    eON_COVER,
};

