#pragma once
#include "CoreMinimal.h"
#include "EDEBUG_FLAG.generated.h"

UENUM(BlueprintType)
enum class EDEBUG_FLAG : uint8 {
    ePLACEMENT_LABEL,
    eNPC_LABEL,
    ePLACEMENT_RESOURCE,
    eNPC_ACTION_ID,
    eNPC_INDEX,
    eNPC_TEXT_LABEL,
    eNPC_FC_LABEL,
    eCHARACTER_ACTION_INFO,
    eCHARACTER_TEXTURE_INFO,
    eNPC_SHOW_TRIGGER,
    ePLAYER_SHOW_TRIGGER,
    eIGNORE_PLACE_NOREACTION_NPC,
    eINPUT_PRIORITY_CONTROLLER,
    eSHOW_CHARA_SOCKET,
    eINVISIBLE_DEBUG_CHARA,
    eENEMY_NAME_OPEN,
    eSIMPLE_ACTION_LOAD,
    eBATTLE_ACTION_IGNORE_LOAD,
    eNPC_PATH_LABEL,
    eENDROLL_FIX_CAMERA_POS_NEAR,
    eENDROLL_FIX_CAMERA_FOCAL_LENGTH_NEAR,
    eENDROLL_FIX_CAMERA_FOCUS_DISTANCE_NEAR,
    eDEBUG_MAX UMETA(Hidden),
};

