#pragma once
#include "CoreMinimal.h"
#include "EFIELD_DISEASE_TYPE.generated.h"

UENUM(BlueprintType)
enum class EFIELD_DISEASE_TYPE : uint8 {
    eNONE,
    eBURNING_FIELD,
    eINTENSE_COLD_FIELD,
    eBURNING_FIELD_COUNTER,
    eINTENSE_COLD_FIELD_COUNTER,
    eSEAL_NORMAL_ATTACK,
    eSEAL_BASE_JOB,
    eSEAL_BACKPACK,
    eSEAL_REVIVE,
    eSEAL_REVIVE_COUNTER,
    eRECOVERY_VALUE_CUT,
    eRECOVERY_VALUE_CUT_COUNTER,
    eBURNING_FIELD_BIRD,
    eBURNING_FIELD_GARUDERA,
    eINTENSE_COLD_FIELD_GARUDERA,
    eDISABLE_ITEM_MENU,
};

