#pragma once
#include "CoreMinimal.h"
#include "EREQUEST_TYPE.generated.h"

UENUM(BlueprintType)
enum class EREQUEST_TYPE : uint8 {
    eNONE,
    eFIELD_TO_BATTLE,
    eBATTLE_TO_FIELD,
    eFIELD_TO_FIELD,
    eGAMEOVER,
    eGO_TO_TITLE,
    eEVENT_START,
    eEVENT_END,
    eBACK_TO_EVENT,
    eEVENT_START_FROM_MAIN_MENU,
    eTHEATER_EVENT_START,
    eTHEATER_EVENT_END,
    eTHEATER_PROLOGUE_START,
    eTHEATER_PROLOGUE_END,
    eTHEATER_PARTCHAT_START,
    eOPEN_MAINMENU,
    eCLOSE_MAINMENU,
    eOPEN_WORLDMAP,
    eCLOSE_WORLDMAP,
    eOPEN_PARTYCHAT,
    eFIELDCOMMAND_MENU_OPEN,
    eFIELDCOMMAND_MENU_CLOSE,
    eFIELDCOMMAND_UNIQUE_MENU_OPEN,
    eFIELDCOMMAND_UNIQUE_MENU_CLOSE,
    eEVENT_TO_FIELDCOMMAND,
    eBATTLE_TO_FIELDCOMMAND,
    eFAST_TRAVEL,
    eTUTORIAL_START_FROM_TRIGGER,
    eMAX,
};

