#pragma once
#include "CoreMinimal.h"
#include "ERICHEVENT_CMD.generated.h"

UENUM(BlueprintType)
enum class ERICHEVENT_CMD : uint8 {
    eNONE,
    eBALLON,
    eNARRATION,
    eTITLEWAIT,
    eFADEIN,
    eFADEOUT,
    eEVENT_FADEIN,
    eEVENT_FADEOUT,
    ePLAY_BGM,
    ePLAY_BGM_MAP,
    ePLAY_BGM_BLOCK,
    eSTOP_BGM,
    ePLAY_SE,
    eCHANGE_VOLUME_ENV,
    eBATTLE,
    eVISIBLE_OBJECT,
    eDIALOG,
    eDIALOG_EVENT,
    eEFFECT,
    eMESSAGEWAIT,
    eNARRATIONWAIT,
    eOPEN_UI,
    eOPEN_TUTORIAL,
    eOPEN_ENDCARD,
    ePOSTEFFECT,
    ePLAY_FC,
    eHOUSE,
    eCHARA_SPAWN,
    eCHARA_ACTION,
    eCHARA_COLLISION,
    eCHARA_POSITION,
    eCHARA_BILLBOARD,
    eATTACH_PLAYER,
    eSUB_SEQ,
    eSUB_SEQ_END,
    eDEEP_DIRECTING,
    eCAMERA,
    eFLASH_BACK_LOAD,
    eFLASH_BACK,
    eBITFLAG,
    eEVENT_GAMEOVER,
    eADD_PPM,
    eTIME,
    eOTHER,
};

