#pragma once
#include "CoreMinimal.h"
#include "ESPACT_MERCHANT_TYPE.generated.h"

UENUM(BlueprintType)
enum class ESPACT_MERCHANT_TYPE : uint8 {
    SPACT_MER_DUMMY,
    SPACT_MER_BUY_ITEM_LOW,
    SPACT_MER_BUY_ITEM_LOW_LOT,
    SPACT_MER_SELL_ITEM_HIGH,
    SPACT_MER_GET_ITEM_LOT,
    SPACT_MER_BUY_ITEM_LOW_HIGH,
    SPACT_MER_FARE_LOW,
    SPACT_MER_INN_LOW,
    SPACT_MER_BTL_CALL_MERCENARY,
    SPACT_MER_BTL_BRIBE,
    SPACT_MER_BTL_COLLECT_MONEY,
    SPACT_MER_BUY_ITEM_LOW_01,
    SPACT_MER_BUY_ITEM_LOW_02,
    SPACT_MER_BUY_ITEM_LOW_03,
    SPACT_MER_BUY_ITEM_LOW_04 = 0x19,
    SPACT_MER_BUY_ITEM_LOW_05,
    SPACT_MER_BUY_ITEM_LOW_06,
    SPACT_MER_BUY_ITEM_LOW_LOT_01 = 0xE,
    SPACT_MER_BUY_ITEM_LOW_LOT_02,
    SPACT_MER_SELL_ITEM_HIGH_01,
    SPACT_MER_SELL_ITEM_HIGH_02,
    SPACT_MER_SELL_ITEM_HIGH_03,
    SPACT_MER_BUY_ITEM_LOW_HIGH_01,
    SPACT_MER_INN_LOW_01,
    SPACT_MER_BTL_CALL_MERCENARY_01,
    SPACT_MER_BTL_CALL_MERCENARY_02,
    SPACT_MER_BTL_BRIBE_01,
    SPACT_MER_BTL_COLLECT_MONEY_01,
    SPACT_MER_MAX = 0x1C UMETA(Hidden),
};

