#pragma once
#include "CoreMinimal.h"
#include "ETutorialCanDisplayFlag.generated.h"

UENUM()
enum class ETutorialCanDisplayFlag {
    NONE,
    BLANCH_MAIN_STORY_FENCER,
    BLANCH_MAIN_STORY_HUNTER,
    BLANCH_MAIN_STORY_ALCHEMIST = 0x4,
    BLANCH_MAIN_STORY_MERCHANT = 0x8,
    BLANCH_MAIN_STORY_PRIEST = 0x10,
    BLANCH_MAIN_STORY_PROFESSOR = 0x20,
    BLANCH_MAIN_STORY_THIEF = 0x40,
    BLANCH_MAIN_STORY_DANCER = 0x80,
    SUB_STORY_MERCHANT = 0x100,
    MAIN_STORY_COUPLING_GAK = 0x200,
    MAIN_STORY_COUPLING_ODO = 0x400,
    MAIN_STORY_COUPLING_SIN = 0x800,
    MAIN_STORY_COUPLING_KUS = 0x1000,
    PROLOUGE_CLEAR = 0x2000,
};

